# Generated by Django 5.2.1 on 2025-05-30 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('engine', models.CharField(choices=[('easyocr', 'EasyOCR'), ('paddleocr', 'PaddleOCR')], max_length=20)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], max_length=10)),
                ('extracted_text', models.TextField()),
                ('confidence_scores', models.JSONField(default=dict)),
                ('average_confidence', models.FloatField(help_text='Porcentaje de confianza entre 0 y 100')),
                ('processing_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
